### ISSUE TITLE
設定の歯車と本情報の歯車　デザイン修正

### ISSUE THREAD

**Issue by aoshi-shinomori** [Gomasy/books-manager#62]
ログイン後、画面左の”設定”アイコンと画面右”リスト表示項目設定"アイコンが被っていて分かりにくいらしい

**Comment by Gomasy** [comment]
ライブラリの方でアイコン固定されてるみたいなのでだめっぽいです。

**Comment by Gomasy** [comment]
615b74a19c9144d5114b8dbe7c11f96bb10d50b6
